version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=<sa_password>
      - MSSQL_PID=Developer
      - MSSQL_TCP_PORT=1433
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql/data/
volumes:
  db-data:
