version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Test123.
      - MSSQL_DB=api_test
      # - MSSQL_PID=Developer
      # - MSSQL_TCP_PORT=1433
      - MSSQL_MEMORY_LIMIT_MB=2048 # Set a memory limit for SQL Server
      # - MSSQL_MAX_MEMORY_MB=512" # Limit SQL Server memory to 512 MB
    ports:
      - "1433:1433"
    volumes:
      - db-Csharp:/var/opt/mssql/data/
volumes:
  db-Csharp:
